apiVersion: argoproj.io/v1aplha1
kind: Application
metadata:
  name: ticketapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/borjanob/DevOps_K8S.git
    targetRevision: HEAD
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: ticketapp

  syncPolicy:
    syncOptions:
      - CreateNamespace = true
  automated:
    selfHeal: true
    prune: true