apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mssql-persistent-volume-claim
  namespace: k8s-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi